In [1]:
import numpy as np
import sys

In [21]:
a = np.array([1,2,3], dtype = 'int16')
print(a)

[1 2 3]


In [22]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[ 9.  8.  7.]
 [ 6.  5.  4.]]


In [23]:
# Get dimension
a.ndim

1

In [24]:
b.ndim

2

In [25]:
a.shape

(3,)

In [26]:
b.shape

(2, 3)

In [27]:
# Get type
print(a.dtype)
print(b.dtype)

int16
float64


In [34]:
# size in bytes
print(a.size)
print(a.nbytes)
# total size = total number of items
print(a.size)
print(b.size)
print(b.nbytes)

3
6
3
6
48


In [35]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [36]:
a.shape

(2, 7)

In [38]:
# get specific element [r, c]
print(a[1,5])
print(a[1,-2])

13
13


In [40]:
# get specific row
print(a[0])
print(a[0, :])

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


In [41]:
# get dpecific column
print(a[:, 2])

[ 3 10]


In [48]:
# gettting a little more fancy [start index:end index:step size]
print(a[0, 1:-1:2])

[2 4 6]


In [49]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [50]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [51]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [53]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [54]:
b.ndim

3

In [56]:
b[0, 1, 1]

4

In [57]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [58]:
# replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [59]:
# all zeros matrix
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [60]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [61]:
np.zeros((2,3,3,2))

array([[[[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]]],


       [[[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]]]])

In [63]:
# all 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [64]:
# any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [65]:
# any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [68]:
# random decimal numbers
np.random.rand(4, 2, 3)

array([[[ 0.73536255,  0.60688863,  0.05644555],
        [ 0.14240236,  0.61980386,  0.01446107]],

       [[ 0.95118107,  0.37783941,  0.61162416],
        [ 0.71541876,  0.81621972,  0.74053954]],

       [[ 0.01224908,  0.96758657,  0.20333822],
        [ 0.94139455,  0.30124035,  0.16968832]],

       [[ 0.14361466,  0.25965663,  0.62249935],
        [ 0.65237128,  0.17729654,  0.735456  ]]])

In [69]:
np.random.random_sample(a.shape)

array([[ 0.12154999,  0.30492057,  0.38632641,  0.28289271,  0.28564302,
         0.43102481,  0.7176721 ],
       [ 0.55333398,  0.68247084,  0.38417629,  0.51312811,  0.17515395,
         0.9589463 ,  0.06953827]])

In [86]:
# random integer values
np.random.randint(4, 7, size=(3,3))

array([[5, 5, 4],
       [6, 6, 5],
       [5, 4, 5]])

In [89]:
# identity matrix
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [93]:
# repeat and array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [94]:
r2 = np.repeat(arr,3, axis=0)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [95]:
r3 = np.repeat(arr,3, axis=1)
print(r3)

[[1 1 1 2 2 2 3 3 3]]


In [100]:
# solution
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1, 1:4] = z
print(output)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 0.  0.  0.]
 [ 0.  9.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  9.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


## be careful

In [101]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]


In [102]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


# Mathematics

In [104]:
a = np.array([1,2,3,4])
print(a+2)
print(a*2)
print(a**2)
print(a/2)
print(a%2)

[3 4 5 6]
[2 4 6 8]
[ 1  4  9 16]
[ 0.5  1.   1.5  2. ]
[1 0 1 0]


In [105]:
b = np.array([1,0,1,0])
print(a+b)

[2 2 4 4]


In [108]:
# take the sin
print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


# Linear Alegebra

In [113]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

c = np.matmul(a,b)
print(c)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[2 2]
 [2 2]
 [2 2]]
[[ 6.  6.]
 [ 6.  6.]]


In [114]:
# find the determinant
c = np.identity(3)
print(np.linalg.det(c))

1.0


In [115]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [116]:
np.min(stats)

1

In [117]:
np.max(stats)

6

In [118]:
np.max(stats, axis=1)

array([3, 6])

In [119]:
np.sum(stats)

21

In [120]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganizing arrays

In [121]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [122]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [124]:
after = before.reshape(4,2)
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [125]:
after = before.reshape(2,2,2)
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [127]:
# vertical stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1, v2, v1, v2]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [131]:
print(np.hstack((v1, v2)))

[1 2 3 4 5 6 7 8]
